
import java.awt.Color;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author maksi
 */
public class Table extends javax.swing.JFrame {

    /**
     * Creates new form Table
     */
    public Table() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jComboBoxColumnSelection = new javax.swing.JComboBox();
        jComboBoxSortingMethod = new javax.swing.JComboBox();
        jTextFieldValueInput = new javax.swing.JTextField();
        jButtonRunSort = new javax.swing.JButton();
        jButtonResetSort = new javax.swing.JButton();
        jScrollPaneTable = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        input1—olumn = new javax.swing.JTextField();
        input2—olumn = new javax.swing.JTextField();
        input3—olumn = new javax.swing.JTextField();
        input5—olumn = new javax.swing.JTextField();
        input4—olumn = new javax.swing.JTextField();
        jButtonAddLine = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SuperMegaGrooveTable");

        jComboBoxColumnSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "—ÚÓÎ·Âˆ 1", "—ÚÓÎ·Âˆ 2", "—ÚÓÎ·Âˆ 3", "—ÚÓÎ·Âˆ 4", "—ÚÓÎ·Âˆ 5" }));
        jComboBoxColumnSelection.setAutoscrolls(true);

        jComboBoxSortingMethod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "<", ">", "=" }));
        jComboBoxSortingMethod.setToolTipText("");

        jButtonRunSort.setText("¬˚ÔÓÎÌËÚ¸");

        jButtonResetSort.setText("—·ÓÒ");
        jButtonResetSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetSortActionPerformed(evt);
            }
        });

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "—ÚÓÎ·Âˆ 1", "—ÚÓÎ·Âˆ 2", "—ÚÓÎ·Âˆ 3", "—ÚÓÎ·Âˆ 4", "—ÚÓÎ·Âˆ 5"
            }
        ));
        mainTable.setCellSelectionEnabled(true);
        jScrollPaneTable.setViewportView(mainTable);

        input1—olumn.setMinimumSize(new java.awt.Dimension(6, 25));

        input2—olumn.setMinimumSize(new java.awt.Dimension(6, 25));

        input3—olumn.setMinimumSize(new java.awt.Dimension(6, 25));

        input5—olumn.setMinimumSize(new java.awt.Dimension(6, 25));

        input4—olumn.setMinimumSize(new java.awt.Dimension(6, 25));

        jButtonAddLine.setText("ƒÓ·‡‚ËÚ¸");
        jButtonAddLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddLineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPaneTable)
                        .addContainerGap())
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(input1—olumn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(input2—olumn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(input3—olumn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(input4—olumn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(input5—olumn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAddLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(jComboBoxColumnSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxSortingMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldValueInput, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRunSort, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jButtonResetSort, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxColumnSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSortingMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValueInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRunSort)
                    .addComponent(jButtonResetSort))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneTable, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input3—olumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input5—olumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input4—olumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input1—olumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input2—olumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddLine))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTextFieldValueInput.getAccessibleContext().setAccessibleParent(jTextFieldValueInput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonResetSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetSortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonResetSortActionPerformed

    private void jButtonAddLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddLineActionPerformed
        DefaultTableModel model = (DefaultTableModel)mainTable.getModel();
        
        try{
            int a = Integer.parseInt(input1—olumn.getText());
            input1—olumn.setBorder(new LineBorder(Color.GRAY, 1));
        }catch(NumberFormatException e){
            input1—olumn.setBorder(new LineBorder(Color.RED, 2));
        }
        
        try{
            int a = Integer.parseInt(input2—olumn.getText());
            input2—olumn.setBorder(new LineBorder(Color.GRAY, 1));
        }catch(NumberFormatException e){
            input2—olumn.setBorder(new LineBorder(Color.RED, 2));
        }
        
        try{
            int a = Integer.parseInt(input3—olumn.getText());
            input3—olumn.setBorder(new LineBorder(Color.GRAY, 1));
        }catch(NumberFormatException e){
            input3—olumn.setBorder(new LineBorder(Color.RED, 2));
        }
        
        try{
            int a = Integer.parseInt(input4—olumn.getText());
            input4—olumn.setBorder(new LineBorder(Color.GRAY, 1));
        }catch(NumberFormatException e){
            input4—olumn.setBorder(new LineBorder(Color.RED, 2));
        }
        
        try{
            int a = Integer.parseInt(input5—olumn.getText());
            input5—olumn.setBorder(new LineBorder(Color.GRAY, 1));
        }catch(NumberFormatException e){
            input5—olumn.setBorder(new LineBorder(Color.RED, 2));
        }
        
        model.addRow(new Object[]{Integer.parseInt(input1—olumn.getText()), Integer.parseInt(input2—olumn.getText()),
        Integer.parseInt(input3—olumn.getText()), Integer.parseInt(input4—olumn.getText()), Integer.parseInt(input5—olumn.getText())});
    }//GEN-LAST:event_jButtonAddLineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField input1—olumn;
    private javax.swing.JTextField input2—olumn;
    private javax.swing.JTextField input3—olumn;
    private javax.swing.JTextField input4—olumn;
    private javax.swing.JTextField input5—olumn;
    private javax.swing.JButton jButtonAddLine;
    private javax.swing.JButton jButtonResetSort;
    private javax.swing.JButton jButtonRunSort;
    private javax.swing.JComboBox jComboBoxColumnSelection;
    private javax.swing.JComboBox jComboBoxSortingMethod;
    private javax.swing.JScrollPane jScrollPaneTable;
    private javax.swing.JTextField jTextFieldValueInput;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable mainTable;
    // End of variables declaration//GEN-END:variables
}
