/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.*;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author maksi
 */
public class Table extends JFrame {

    /**
     * Creates new form Table
     */
    public Table() {
        initComponents();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new JPanel();
        jComboBoxColumnSelection = new JComboBox();
        jComboBoxFilterMethod = new JComboBox();
        jTextFieldValueInput = new JTextField();
        jButtonRunFilter = new JButton();
        jButtonResetFilter = new JButton();
        jScrollPaneTable = new JScrollPane();
        mainTable = new JTable(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        input1Column = new JTextField();
        input2Column = new JTextField();
        input3Column = new JTextField();
        input5Column = new JTextField();
        input4Column = new JTextField();
        jButtonAddLine = new JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SuperMegaGrooveTable");
        jTextFieldValueInput.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent documentEvent) {
                RunFilter();
            }
            @Override
            public void removeUpdate(DocumentEvent documentEvent) {
                RunFilter();
            }
            @Override
            public void changedUpdate(DocumentEvent documentEvent) {
                RunFilter();
            }
        });
        jComboBoxFilterMethod.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                RunFilter();
            }
        });
        jComboBoxColumnSelection.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                RunFilter();
            }
        });

        jComboBoxColumnSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "Столбец 1", "Столбец 2", "Столбец 3", "Столбец 4", "Столбец 5" }));
        jComboBoxColumnSelection.setAutoscrolls(true);

        jComboBoxFilterMethod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "<", ">", "=" }));
        jComboBoxFilterMethod.setToolTipText("");

        jButtonRunFilter.setText("Выполнить");
        jButtonRunFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunFilter();
            }
        });

        jButtonResetFilter.setText("Сброс");
        jButtonResetFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetSortActionPerformed(evt);
            }
        });

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Столбец 1", "Столбец 2", "Столбец 3", "Столбец 4", "Столбец 5"
            }
        ));
        mainTable.setCellSelectionEnabled(true);
        jScrollPaneTable.setViewportView(mainTable);

        input1Column.setMinimumSize(new java.awt.Dimension(6, 25));

        input2Column.setMinimumSize(new java.awt.Dimension(6, 25));

        input3Column.setMinimumSize(new java.awt.Dimension(6, 25));

        input5Column.setMinimumSize(new java.awt.Dimension(6, 25));

        input4Column.setMinimumSize(new java.awt.Dimension(6, 25));

        jButtonAddLine.setText("Добавить");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPaneTable)
                        .addContainerGap())
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(input1Column, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(input2Column, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(input3Column, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(input4Column, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(input5Column, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAddLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(jComboBoxColumnSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxFilterMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldValueInput, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRunFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jButtonResetFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxColumnSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxFilterMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValueInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRunFilter)
                    .addComponent(jButtonResetFilter))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneTable, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input3Column, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input5Column, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input4Column, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input1Column, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input2Column, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddLine))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTextFieldValueInput.getAccessibleContext().setAccessibleParent(jTextFieldValueInput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonResetSortActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonResetSortActionPerformed
        
        jComboBoxColumnSelection.setSelectedIndex(0);
        jComboBoxFilterMethod.setSelectedIndex(0);
        jTextFieldValueInput.setText("");
        
        mainTable.setRowSorter(null);
        
    }//GEN-LAST:event_jButtonResetSortActionPerformed

    private void RunFilter() {//GEN-FIRST:event_jButtonRunSortActionPerformed
       
        Integer column = jComboBoxColumnSelection.getSelectedIndex() - 1;
        Integer filterMethod = jComboBoxFilterMethod.getSelectedIndex();
        Integer filterValue;
        try{
            filterValue = Integer.parseInt(jTextFieldValueInput.getText());
            jTextFieldValueInput.setBorder(getDefaultBorder());
        }
        catch (NumberFormatException e){
            jTextFieldValueInput.setBorder(getErrorBorder());
            return;
        }
        if(filterMethod == -1 || column==-1){
            return;
        }

        
        RowFilter<Object, Object> filter = new RowFilter<Object, Object>() {
            public boolean include(Entry entry) {
                Integer value = (Integer) entry.getValue(column);
                
                if (value == null) return false;
                
                switch(filterMethod)
                {
                    case 1: return value < filterValue;
                    case 2: return value > filterValue;
                    case 3: return value.intValue() == filterValue;
                }
                
                return false;
            }
        };
        
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(mainTable.getModel());
        sorter.setRowFilter(filter);
        mainTable.setRowSorter(sorter);
        
    }//GEN-LAST:event_jButtonRunSortActionPerformed
    private void addLine(){
        Integer[] l = new Integer[5];
        int index = 0;
        boolean valid = true;
        for (JTextField input: getNewLineInputs()) {
            try{
                l[index] = Integer.parseInt(input.getText());
                input.setBorder(getDefaultBorder());
            } catch (NumberFormatException e){
                valid = false;
                input.setBorder(getErrorBorder());
            }
            index++;
        }
        if(valid){
            addRow(l);
            for(JTextField input: getNewLineInputs()){
                input.setText("");
            }
        }
    }
    void populateTable(){
        Random random = new Random();
        for(int i = 0; i < 5; i++){
            Integer[] arr = new Integer[5];
            for(int j = 0; j<5; j++){
                arr[j] = random.nextInt(50);
            }
            addRow(arr);
        }
    }
    Border getErrorBorder(){
        return new LineBorder(Color.RED, 2);
    }
    Border getDefaultBorder(){
        return new JTextField().getBorder();
    }
    void addRow(Integer[] array){
        DefaultTableModel model = (DefaultTableModel) mainTable.getModel();
        model.addRow(array);
    }


    JTextField[] getNewLineInputs(){
        return new JTextField[]{
                input1Column,
                input2Column,
                input3Column,
                input4Column,
                input5Column
        };
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JTextField input1Column;
    private JTextField input2Column;
    private JTextField input3Column;
    private JTextField input4Column;
    private JTextField input5Column;
    private JButton jButtonAddLine;
    private JButton jButtonResetFilter;
    private JButton jButtonRunFilter;
    private JComboBox jComboBoxColumnSelection;
    private JComboBox jComboBoxFilterMethod;
    private JScrollPane jScrollPaneTable;
    private JTextField jTextFieldValueInput;
    private JPanel mainPanel;
    private JTable mainTable;
    // End of variables declaration//GEN-END:variables
}
